#define UNCERT_SIM_ 1e-3 //2 mm == 0.002

#define NOT_INIT_OBJECT_TRANPORT_FUNCTION -100

#define PARCER_NO_EQUAL_CHARACTER -101
#define PARCER_EMPTY_STRING -102
#define PARCER_WRONG_STRING_FORMAT -103
#define PARCER_EMPTY_VALUE -104
#define PARCER_WRONG_DOUBLE_FORMAT -105
#define PARCER_HOME_DIR_ERROR -106
#define PARCER_HOME_FILE_ERROR -107
#define PARCER_NO_HOME_FILE_EXIST -108

#define NO_LOCAL_OVERRIDE -109

#define D_MAP_NO_SUCH_PARAMETERS -111
#define D_MAP_KEY_ALREADY_EXISTS -112
#define D_MAP_NOT_FOUND_DEFAULT_LIMIT -113
#define D_MAP_NOT_FOUND_DEFAULT_LIMIT_PREFS_KEY -114
#define D_MAP_NOT_LIMIT_SIZE_MISMATCH -115
#define TR_WRONG_S_PARAMETER -116
#define TR_WRONG_SORT_PARAMETER_NAME -117
#define TR_WRONG_LOCAL_LIMITS	-118
#define TR_NOT_DOUBLE_PAR_IN_MATRIX_BUILD	-119
#define TR_BEAM_INITIAL_POS_MISSING -120
#define TR_EMPTY_MTR_MAPS	-121
#define TR_MTR_WRONG_MIN_MAX_VALUES -122
//division by 0 in matrix build
#define TR_NUM_OF_MESUREMENTS_PAR_MISSING -123
#define TR_REJECTION_CRITERION_PAR_MISSING -124
#define A_PARCER_NO_G_METHOD_NUM	-125
#define A_PARCER_NO_OBJECT_NUM		-126
#define A_PARCER_NO_METHOD_NUM		-127